In [80]:
# 导包
import numpy as np

# 1.Numpy的属性介绍

In [81]:

# numpy的数组 => ndarray， 他是多维的，并且是固定类型的，主要用于矩阵运算

# 导包

# import numpy as np

arr1 = np.arange(15).reshape(3,5)

print(arr1)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [82]:
print(f'arr1的维度: {arr1.ndim}')
print(f'arr1的轴数: {arr1.ndim}')

arr1的维度: 2
arr1的轴数: 2


In [83]:
print(f'arr1的形状: {arr1.shape}')

arr1的形状: (3, 5)


In [84]:
print(f'arr1的元素类型: {arr1.dtype}')

arr1的元素类型: int64


In [85]:
print(f'arr1的元素个数: {arr1.size}')

arr1的元素个数: 15


In [86]:
# 一个字节占8位, 所以int64 / 8 = 8.
print(f'arr1的元素占用字节数: {arr1.itemsize}')

arr1的元素占用字节数: 8


In [87]:
print(f'arr1的类型: {type(arr1)}')

arr1的类型: <class 'numpy.ndarray'>


# 2.创建ndarray对象

### 2.1 通过np.array函数创建

In [88]:
# 创建python列表
py_list = [11,22,33,44,55]
# 把python列表转为nbarray对象
arr2 = np.array(py_list)

In [89]:
print(f'arr2 = {arr2}')

arr2 = [11 22 33 44 55]


In [90]:
print(f'arr2的类型 = {type(arr2)}')

arr2的类型 = <class 'numpy.ndarray'>


### 2.2 通过np.arange函数创建

In [91]:
# arange(起始, 结束, 步长, dtype=np.类型)
arr3 = np.arange(0,10,2,dtype=np.float64)

In [92]:
print(f'arr3 = {arr3}')

arr3 = [0. 2. 4. 6. 8.]


In [93]:
print(f'arr3的元素类型 = {arr3.dtype}')

arr3的元素类型 = float64


### 2.3 随机数函数创建

In [94]:
# np.random.rand(行，列) 生成 0.0 ~ 1.0 之间的随机小数矩阵
arr4 = np.random.rand(3,5)

In [95]:
print(f'arr4 = {arr4}')

arr4 = [[0.35141414 0.14944775 0.45471075 0.89876581 0.85854632]
 [0.8476124  0.93023988 0.88572609 0.25391784 0.11989277]
 [0.58690042 0.00868021 0.05308154 0.47133184 0.17949342]]


In [96]:
# np.random.uniform(起始，结束，size=(行，列)) 生成指定范围的小数矩阵
arr5 = np.random.uniform(3,9,size=(2,6))

In [97]:
print(f'arr5 = {arr5}')

arr5 = [[4.67613762 3.60966493 7.52237018 3.35511631 4.07850188 6.21777306]
 [6.10099936 8.05836631 3.09506852 8.64432966 3.51633621 3.77883291]]


# 3.类型转换

In [98]:
# 创建ndarray对象
arr6 = np.arange(0,10,2,dtype=np.int32)

In [99]:
# 把上述的array对象的元素类型从 int32 转换为 float32
arr7 = arr6.astype(np.float32)

In [100]:
print(f'arr7 = {arr7}')

arr7 = [0. 2. 4. 6. 8.]


In [101]:
print(f'arr6的元素类型 = {arr6.dtype}')

arr6的元素类型 = int32


In [102]:
print(f'arr7的元素类型 = {arr7.dtype}')

arr7的元素类型 = float32


# 4.创建等比和等差数列

In [103]:
# 等比数列
# np.logspace(起始指数，结束指数，元素长度，base=基数)
# 表示 2的0次幂, 2的9次幂，长度为10，基数为2的一个数组
arr8 = np.logspace(0,9,10,base=2)

print(f'arr8 = {arr8}')

arr8 = [  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


In [104]:
# 等差数列
# np.linspace(起始值，结束值，元素长度)
arr9 = np.linspace(1,10,10)
print(f'arr9 = {arr9}')

arr9 = [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


# 5.NumPy常用函数

### 5.1 基本函数

In [105]:
# 创建标准的正态分布的序列
arr10 = np.random.randn(3,5);
print(arr10);

[[ 0.34663512 -1.3344745  -0.34609668  1.22306973  0.0352699 ]
 [-0.33736786 -1.20636624 -0.16851056  0.75008545  0.04094769]
 [-0.10345666  0.90877382 -0.11578587 -0.43240994  0.06250616]]


In [106]:
# print(f'np.ceil(arr10) = {np.ceil(arr10)}')
# print(f'np.floor(arr10) = {np.floor(arr10)}')
# print(f'np.rint(arr10) = {np.rint(arr10)}')
# print(f'np.abs(arr10) = {np.abs(arr10)} \n')
# 矩阵乘法(行列数一致)
# print(f'np.multiply(arr10,arr10) = {np.multiply(arr10,arr10)}')
# print(f'arr10 * arr10 = {arr10 * arr10}')
# 矩阵除法(行列数一致)
# print(f'np.divide(arr10,arr10) = {np.divide(arr10,arr10)}')
print(f'np.where(arr10 > 0, 1, -1) = {np.where(arr10 > 0, 1, -1)}')




np.where(arr10 > 0, 1, -1) = [[ 1 -1 -1  1  1]
 [-1 -1 -1  1  1]
 [-1  1 -1 -1  1]]


### 5.2 统计函数

In [107]:
# 定义ndarray对象
arr11 = np.arange(12).reshape(3,4);
print(f'arr11 = {arr11}');

arr11 = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [108]:
# print(f'np.cumsum(arr11) = {np.cumsum(arr11)}');
# print(f'np.sum(arr11) = {np.sum(arr11)}');
# print(f'np.sum(arr11,axis=0) = {np.sum(arr11,axis=0)}');
# print(f'np.sum(arr11,axis=0) = {np.sum(arr11,axis=1)}');

### 5.3 去重和排序

In [109]:
# 定义数组
arr12 = np.array([[1,2,1],[2,3,5]])
arr13 = np.array([1,3,5,7,2,4,6,8])
print(f'arr12 = {arr12}')
print(f'arr13 = {arr13}')

arr12 = [[1 2 1]
 [2 3 5]]
arr13 = [1 3 5 7 2 4 6 8]


In [110]:
# 元素去重
print(f'np.unique(arr12) = {np.unique(arr12)}')
# 元素排序
print(f'np.sort(arr13) = {np.sort(arr13)}')

np.unique(arr12) = [1 2 3 5]
np.sort(arr13) = [1 2 3 4 5 6 7 8]


 ### 5.4 矩阵运算

In [111]:
# 定义数组
arr14 = np.array([[1,2,3],[4,5,6]])
arr15 = np.array([[1,2],[3,4],[5,6]])
print(f'arr14 = {arr14}')
print(f'arr15 = {arr15}')

arr14 = [[1 2 3]
 [4 5 6]]
arr15 = [[1 2]
 [3 4]
 [5 6]]


In [115]:
print(f'arr14 @ arr15 = {arr14 @ arr15}')
print(f'np.dot(arr14,arr15) = {np.dot(arr14,arr15)}')


arr14 @ arr15 = [[22 28]
 [49 64]]
np.dot(arr14,arr15) = [[22 28]
 [49 64]]
